// src/renderer/angular-renderer.ts
import type { DocumentNode, NodeOf, RenderHelpers, RenderOptions, RenderResult, WiremdNode } from '../types.js';
import { getStyleCSS } from './styles.js';
import {
  analyzeFrameworkState,
  buildAnnotationText,
  buildPrefixedClasses,
  buildResponsiveGridClasses,
  escapeHtml,
  escapeJsString,
  getStates,
  getIconGlyph,
  isAnnotationOnlyNode,
  repeatString,
} from './plugin-utils.js';

interface AngularOptions extends RenderOptions {
  componentName?: string;
  selector?: string;
  standalone?: boolean;
  inlineStyles?: boolean;
}

interface AngularContext {
  classPrefix: string;
  analysis: ReturnType<typeof analyzeFrameworkState>;
  helpers: RenderHelpers;
  showAnnotations: boolean;
}

export function renderAngularArtifacts(
  ast: DocumentNode,
  options: AngularOptions = {},
  helpers: RenderHelpers,
): RenderResult {
  const classPrefix = options.classPrefix || 'wmd-';
  const componentName = options.componentName || 'WiremdComponent';
  const selector = options.selector || `app-${helpers.toKebabCase(componentName, 'wiremd')}`;
  const standalone = options.standalone !== false;
  const analysis = analyzeFrameworkState(ast, helpers);
  const context: AngularContext = {
    classPrefix,
    analysis,
    helpers,
    showAnnotations: Boolean(options.showAnnotations),
  };
  const baseName = `${helpers.toKebabCase(componentName, 'wiremd')}.component`;
  const template = `<div class="${classPrefix}root ${classPrefix}${options.style || 'sketch'}">\n${ast.children.map((child) => renderAngularNode(child, context, 0)).join('\n')}\n</div>`;
  const styles = getStyleCSS(options.style || 'sketch', classPrefix);
  const componentTs = renderAngularComponentTs(componentName, selector, baseName, analysis, styles, standalone, Boolean(options.inlineStyles));

  const artifacts = [
    { filename: `${baseName}.ts`, content: componentTs },
    { filename: `${baseName}.html`, content: template },
  ];

  if (!options.inlineStyles) {
    artifacts.push({ filename: `${baseName}.css`, content: styles });
  }

  return {
    format: 'angular',
    artifacts,
  };
}

function renderAngularComponentTs(
  componentName: string,
  selector: string,
  baseName: string,
  analysis: ReturnType<typeof analyzeFrameworkState>,
  styles: string,
  standalone: boolean,
  inlineStyles: boolean,
): string {
  const controls = analysis.fields.length === 0
    ? '    placeholder: this.fb.control(\'\'),'
    : analysis.fields.map((field) => `    ${field.key}: this.fb.control(${renderAngularValue(field.initialValue)}),`).join('\n');
  const styleMetadata = inlineStyles
    ? `styles: [\`${styles.replace(/`/g, '\\`')}\`]`
    : `styleUrls: ['./${baseName}.css']`;
  const standaloneMetadata = standalone ? '  standalone: true,\n  imports: [CommonModule, ReactiveFormsModule],\n' : '';

  return `import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: '${selector}',
${standaloneMetadata}  templateUrl: './${baseName}.html',
  ${styleMetadata},
})
export class ${componentName} {
  @Output() submitted = new EventEmitter<Record<string, unknown>>();
  @Output() buttonClick = new EventEmitter<string>();

  readonly form = this.fb.group({
${controls}
  });

  constructor(private readonly fb: FormBuilder) {}

  handleSubmit(): void {
    this.submitted.emit(this.form.getRawValue() as Record<string, unknown>);
  }

  handleButtonClick(label: string): void {
    this.buttonClick.emit(label);
  }
}`;
}

function renderAngularNode(node: WiremdNode, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);

  if (isAnnotationOnlyNode(node) && !context.showAnnotations) {
    return '';
  }

  let rendered: string;

  switch (node.type) {
    case 'button':
      rendered = renderAngularButton(node, context, indent);
      break;
    case 'input':
      rendered = renderAngularInput(node, context, indent);
      break;
    case 'textarea':
      rendered = renderAngularTextarea(node, context, indent);
      break;
    case 'select':
      rendered = renderAngularSelect(node, context, indent);
      break;
    case 'checkbox':
      rendered = renderAngularCheckbox(node, context, indent);
      break;
    case 'radio':
      rendered = renderAngularRadio(node, context, indent);
      break;
    case 'radio-group':
      rendered = renderAngularWrapper('div', 'radio-group', node.children, node.props, context, indent);
      break;
    case 'icon':
      rendered = `${spaces}<span class="${buildPrefixedClasses(context.classPrefix, 'icon', node.props)}" data-icon="${escapeHtml(node.props.name)}" aria-label="${escapeHtml(node.props.name)}">${getIconGlyph(node.props.name)}</span>`;
      break;
    case 'container':
      rendered = renderAngularWrapper('div', `container-${node.containerType}`, node.children, node.props, context, indent);
      break;
    case 'nav':
      rendered = renderAngularWrapper('nav', 'nav', node.children, node.props, context, indent);
      break;
    case 'nav-item':
      rendered = renderAngularNavItem(node, context, indent);
      break;
    case 'brand':
      rendered = renderAngularWrapper('div', 'brand', node.children, node.props, context, indent);
      break;
    case 'grid':
      rendered = renderAngularGrid(node, context, indent);
      break;
    case 'grid-item':
      rendered = renderAngularWrapper('div', 'grid-item', node.children, node.props, context, indent);
      break;
    case 'form':
      rendered = renderAngularForm(node, context, indent);
      break;
    case 'heading':
      rendered = renderAngularHeading(node, context, indent);
      break;
    case 'paragraph':
      rendered = renderAngularParagraph(node, context, indent);
      break;
    case 'text':
      rendered = `${spaces}${escapeHtml(node.content)}`;
      break;
    case 'image':
      rendered = renderAngularImage(node, context, indent);
      break;
    case 'link':
      rendered = renderAngularLink(node, context, indent);
      break;
    case 'list':
      rendered = renderAngularList(node, context, indent);
      break;
    case 'list-item':
      rendered = renderAngularListItem(node, context, indent);
      break;
    case 'table':
      rendered = renderAngularTable(node, context, indent);
      break;
    case 'table-header':
      rendered = renderAngularTableHeader(node, context, indent);
      break;
    case 'table-row':
      rendered = renderAngularTableRow(node, context, indent);
      break;
    case 'table-cell':
      rendered = renderAngularTableCell(node, context, indent);
      break;
    case 'blockquote':
      rendered = renderAngularWrapper('blockquote', 'blockquote', node.children, node.props, context, indent);
      break;
    case 'code':
      rendered = renderAngularCode(node, context, indent);
      break;
    case 'separator':
      rendered = `${spaces}<hr class="${buildPrefixedClasses(context.classPrefix, 'separator', node.props)}" />`;
      break;
    case 'alert':
      rendered = renderAngularWrapper('div', `state-${node.alertType}`, node.children, node.props, context, indent);
      break;
    case 'badge':
      rendered = `${spaces}<span class="${buildPrefixedClasses(context.classPrefix, 'badge', node.props)}">${escapeHtml(node.content)}</span>`;
      break;
    case 'loading-state':
      rendered = renderAngularStateBlock(node.message || 'Loading...', node.children || [], node.props, context, indent, 'clock', 'loading-state');
      break;
    case 'empty-state':
      rendered = renderAngularStateBlock(node.title || 'Empty state', node.children, node.props, context, indent, node.icon, 'empty-state');
      break;
    case 'error-state':
      rendered = renderAngularStateBlock(node.title || 'Error state', node.children, node.props, context, indent, node.icon, 'error-state');
      break;
    default:
      rendered = `${spaces}<!-- Unsupported node type: ${(node as { type: string }).type} -->`;
      break;
  }

  return appendAngularAnnotationMarkup(rendered, ('props' in node && node.props) ? node.props : {}, context, indent);
}

function renderAngularButton(node: NodeOf<'button'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'button', node.props);
  const buttonType = node.props.type || (node.props.variant === 'primary' ? 'submit' : 'button');
  const disabled = (node.props.disabled || getStates(node.props).includes('disabled')) ? ' disabled' : '';
  const clickHandler = buttonType === 'submit' ? '' : ` (click)="handleButtonClick('${escapeHtml(node.content || 'button')}')"`;
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<button class="${classes}" type="${buttonType}"${disabled}${clickHandler}>${content}</button>`;
}

function renderAngularInput(node: NodeOf<'input'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'input', node.props);
  const field = context.analysis.nodeBindings.get(node) || context.helpers.toIdentifier(node.props.placeholder as string || 'field', 'field');
  const placeholder = node.props.placeholder ? ` placeholder="${escapeHtml(node.props.placeholder)}"` : '';
  const disabled = (node.props.disabled || getStates(node.props).includes('disabled')) ? ' disabled' : '';
  return `${spaces}<input [formControl]="form.controls.${field}" type="${node.props.inputType || node.props.type || 'text'}" class="${classes}"${placeholder}${disabled} />`;
}

function renderAngularTextarea(node: NodeOf<'textarea'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'textarea', node.props);
  const field = context.analysis.nodeBindings.get(node) || context.helpers.toIdentifier(node.props.placeholder as string || 'field', 'field');
  return `${spaces}<textarea [formControl]="form.controls.${field}" class="${classes}"></textarea>`;
}

function renderAngularSelect(node: NodeOf<'select'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'select', node.props);
  const field = context.analysis.nodeBindings.get(node) || context.helpers.toIdentifier(node.props.placeholder as string || 'select', 'select');
  const options = node.options
    .map((option) => `${spaces}  <option value="${escapeHtml(option.value)}">${escapeHtml(option.label)}</option>`)
    .join('\n');
  return `${spaces}<select [formControl]="form.controls.${field}" class="${classes}">\n${options}\n${spaces}</select>`;
}

function renderAngularCheckbox(node: NodeOf<'checkbox'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'checkbox', node.props);
  const field = context.analysis.nodeBindings.get(node) || context.helpers.toIdentifier(node.label || 'checkbox', 'checkbox');
  const label = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.label || '');
  return `${spaces}<label class="${classes}"><input [formControl]="form.controls.${field}" type="checkbox" /> <span>${label}</span></label>`;
}

function renderAngularRadio(node: NodeOf<'radio'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'radio', node.props);
  const field = context.analysis.nodeBindings.get(node) || context.helpers.toIdentifier(node.label, 'radioGroup');
  const value = escapeHtml(typeof node.props.value === 'string' ? node.props.value : node.label);
  return `${spaces}<label class="${classes}"><input [formControl]="form.controls.${field}" type="radio" value="${value}" /> <span>${escapeHtml(node.label)}</span></label>`;
}

function renderAngularForm(node: NodeOf<'form'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'form', node.props);
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 1)).join('\n');
  return `${spaces}<form [formGroup]="form" class="${classes}" (ngSubmit)="handleSubmit()">\n${children}\n${spaces}</form>`;
}

function renderAngularHeading(node: NodeOf<'heading'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, `h${node.level}`, node.props);
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<h${node.level} class="${classes}">${content}</h${node.level}>`;
}

function renderAngularParagraph(node: NodeOf<'paragraph'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'paragraph', node.props);
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<p class="${classes}">${content}</p>`;
}

function renderAngularImage(node: NodeOf<'image'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'image', node.props);
  return `${spaces}<img src="${escapeHtml(node.src)}" alt="${escapeHtml(node.alt)}" class="${classes}" />`;
}

function renderAngularLink(node: NodeOf<'link'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'link', node.props);
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<a href="${escapeHtml(node.href)}" class="${classes}">${content}</a>`;
}

function renderAngularList(node: NodeOf<'list'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const tag = node.ordered ? 'ol' : 'ul';
  const classes = buildPrefixedClasses(context.classPrefix, 'list', node.props);
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 1)).join('\n');
  return `${spaces}<${tag} class="${classes}">\n${children}\n${spaces}</${tag}>`;
}

function renderAngularListItem(node: NodeOf<'list-item'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'list-item', node.props);
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<li class="${classes}">${content}</li>`;
}

function renderAngularTable(node: NodeOf<'table'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'table', node.props);
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 1)).join('\n');
  return `${spaces}<table class="${classes}">\n${children}\n${spaces}</table>`;
}

function renderAngularTableHeader(node: NodeOf<'table-header'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 2)).join('\n');
  return `${spaces}<thead>\n${spaces}  <tr>\n${children}\n${spaces}  </tr>\n${spaces}</thead>`;
}

function renderAngularTableRow(node: NodeOf<'table-row'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 1)).join('\n');
  return `${spaces}<tr>\n${children}\n${spaces}</tr>`;
}

function renderAngularTableCell(node: NodeOf<'table-cell'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const tag = node.header ? 'th' : 'td';
  const classes = buildPrefixedClasses(context.classPrefix, `table-cell ${context.classPrefix}align-${node.align || 'left'}`, {});
  const content = node.children && node.children.length > 0
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<${tag} class="${classes}">${content}</${tag}>`;
}

function renderAngularCode(node: NodeOf<'code'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  if (node.inline !== false) {
    return `${spaces}<code class="${buildPrefixedClasses(context.classPrefix, 'code-inline', {})}">${escapeHtml(node.value)}</code>`;
  }

  return `${spaces}<pre class="${buildPrefixedClasses(context.classPrefix, 'code-block', {})}"><code>${escapeHtml(node.value)}</code></pre>`;
}

function renderAngularGrid(node: NodeOf<'grid'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const responsiveClass = buildResponsiveGridClasses(context.classPrefix, node.props?.responsive?.gridColumns);
  const classes = `${buildPrefixedClasses(context.classPrefix, 'grid', node.props)} ${context.classPrefix}grid-${node.columns}${responsiveClass ? ` ${responsiveClass}` : ''}`;
  const children = node.children.map((child) => renderAngularNode(child, context, indent + 1)).join('\n');
  return `${spaces}<div class="${classes}" style="--grid-columns: ${node.columns}">\n${children}\n${spaces}</div>`;
}

function renderAngularNavItem(node: NodeOf<'nav-item'>, context: AngularContext, indent: number): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, 'nav-item', node.props);
  const content = node.children
    ? node.children.map((child) => renderAngularNode(child, context, -1)).join('')
    : escapeHtml(node.content || '');
  return `${spaces}<a href="${escapeHtml(node.href || '#')}" class="${classes}">${content}</a>`;
}

function renderAngularWrapper(
  tag: string,
  baseClass: string,
  children: WiremdNode[],
  props: Record<string, unknown>,
  context: AngularContext,
  indent: number,
): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = buildPrefixedClasses(context.classPrefix, baseClass, props);
  const content = children.map((child) => renderAngularNode(child, context, indent + 1)).filter(Boolean).join('\n');
  return `${spaces}<${tag} class="${classes}">\n${content}\n${spaces}</${tag}>`;
}

function renderAngularStateBlock(
  title: string,
  children: WiremdNode[],
  props: Record<string, unknown>,
  context: AngularContext,
  indent: number,
  icon?: string,
  stateKind = 'empty-state',
): string {
  const spaces = repeatString('  ', indent + 1);
  const classes = `${buildPrefixedClasses(context.classPrefix, 'state-block', props)} ${context.classPrefix}container-${stateKind}`;
  const content = children.map((child) => renderAngularNode(child, context, indent + 1)).filter(Boolean).join('\n');
  const iconMarkup = icon ? `<span data-icon="${escapeHtml(icon)}">${getIconGlyph(icon)}</span>` : '';
  return `${spaces}<div class="${classes}">\n${spaces}  <strong>${iconMarkup}${escapeHtml(title)}</strong>\n${content ? `${content}\n` : ''}${spaces}</div>`;
}

function appendAngularAnnotationMarkup(
  rendered: string,
  props: Record<string, unknown>,
  context: AngularContext,
  indent: number,
): string {
  if (!context.showAnnotations) {
    return rendered;
  }

  const annotationText = buildAnnotationText(props);
  if (!annotationText) {
    return rendered;
  }

  const spaces = repeatString('  ', indent + 1);
  return `${rendered}\n${spaces}<aside class="${context.classPrefix}annotation-callout">${escapeHtml(annotationText)}</aside>`;
}

function renderAngularValue(value: string | boolean | string[]): string {
  if (Array.isArray(value)) {
    return `[${value.map((entry) => `'${escapeJsString(entry)}'`).join(', ')}]`;
  }
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  return `'${escapeJsString(value)}'`;
}

// src/renderer/react-renderer.ts
/**
 * React/JSX Renderer for wiremd AST nodes
 * Converts AST nodes to React functional components with TypeScript
 *
 * Copyright (c) 2025 wiremd
 * Licensed under MIT License
 * https://github.com/akonan/wiremd/blob/main/LICENSE
 */

import type { WiremdNode } from '../types.js';

export interface ReactRenderContext {
  classPrefix: string;
  typescript: boolean;
  useClassName: boolean; // true = className, false = class
  componentName?: string;
  nextId(prefix?: string): string;
  showAnnotations?: boolean;
}

/**
 * Helper to repeat string (ES5 compatible)
 */
function repeatString(str: string, count: number): string {
  let result = '';
  for (let i = 0; i < count; i++) {
    result += str;
  }
  return result;
}

/**
 * Render a wiremd AST node to React/JSX
 */
export function renderNode(node: WiremdNode, context: ReactRenderContext, indent = 0): string {
  if (isAnnotationOnlyNode(node) && !context.showAnnotations) {
    return '';
  }

  const indentStr = repeatString('  ', indent);
  let rendered = '';

  switch (node.type) {
    case 'button':
      rendered = renderButton(node, context, indent);
      break;

    case 'input':
      rendered = renderInput(node, context, indent);
      break;

    case 'textarea':
      rendered = renderTextarea(node, context, indent);
      break;

    case 'select':
      rendered = renderSelect(node, context, indent);
      break;

    case 'checkbox':
      rendered = renderCheckbox(node, context, indent);
      break;

    case 'radio':
      rendered = renderRadio(node, context, indent);
      break;

    case 'radio-group':
      rendered = renderRadioGroup(node, context, indent);
      break;

    case 'icon':
      rendered = renderIcon(node, context, indent);
      break;

    case 'container':
      rendered = renderContainer(node, context, indent);
      break;

    case 'nav':
      rendered = renderNav(node, context, indent);
      break;

    case 'nav-item':
      rendered = renderNavItem(node, context, indent);
      break;

    case 'brand':
      rendered = renderBrand(node, context, indent);
      break;

    case 'grid':
      rendered = renderGrid(node, context, indent);
      break;

    case 'grid-item':
      rendered = renderGridItem(node, context, indent);
      break;

    case 'heading':
      rendered = renderHeading(node, context, indent);
      break;

    case 'paragraph':
      rendered = renderParagraph(node, context, indent);
      break;

    case 'text':
      rendered = renderText(node, context, indent);
      break;

    case 'image':
      rendered = renderImage(node, context, indent);
      break;

    case 'link':
      rendered = renderLink(node, context, indent);
      break;

    case 'list':
      rendered = renderList(node, context, indent);
      break;

    case 'list-item':
      rendered = renderListItem(node, context, indent);
      break;

    case 'table':
      rendered = renderTable(node, context, indent);
      break;

    case 'table-header':
      rendered = renderTableHeader(node, context, indent);
      break;

    case 'table-row':
      rendered = renderTableRow(node, context, indent);
      break;

    case 'table-cell':
      rendered = renderTableCell(node, context, indent);
      break;

    case 'blockquote':
      rendered = renderBlockquote(node, context, indent);
      break;

    case 'code':
      rendered = renderCode(node, context, indent);
      break;

    case 'separator':
      rendered = renderSeparator(node, context, indent);
      break;

    case 'loading-state':
      rendered = renderStateBlock(node, context, indent, 'loading-state', node.message || 'Loading...', 'clock');
      break;

    case 'empty-state':
      rendered = renderStateBlock(node, context, indent, 'empty-state', node.title || 'Empty state', node.icon);
      break;

    case 'error-state':
      rendered = renderStateBlock(node, context, indent, 'error-state', node.title || 'Error state', node.icon);
      break;

    default:
      rendered = `${indentStr}{/* Unknown node type: ${(node as any).type} */}`;
      break;
  }

  return appendAnnotationJSX(rendered, node, context, indentStr);
}

function renderButton(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'button', node.props);
  const disabled = hasState(node.props, 'disabled') || node.props.disabled;
  const classAttr = context.useClassName ? 'className' : 'class';

  const contentJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content);

  return `${indentStr}<button ${classAttr}="${classes}"${disabled ? ' disabled' : ''}>\n${indentStr}  ${contentJSX}\n${indentStr}</button>`;
}

function renderInput(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'input', node.props);
  const type = node.props.inputType || node.props.type || 'text';
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.placeholder) attrs.push(`placeholder="${escapeJSX(node.props.placeholder)}"`);
  if (node.props.value) attrs.push(`defaultValue="${escapeJSX(node.props.value)}"`);
  if (node.props.required) attrs.push('required');
  if (node.props.disabled || hasState(node.props, 'disabled')) attrs.push('disabled');

  return `${indentStr}<input type="${type}" ${classAttr}="${classes}" ${attrs.join(' ')} />`;
}

function renderTextarea(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'textarea', node.props);
  const rows = node.props.rows || 4;
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.placeholder) attrs.push(`placeholder="${escapeJSX(node.props.placeholder)}"`);
  if (node.props.required) attrs.push('required');
  if (node.props.disabled || hasState(node.props, 'disabled')) attrs.push('disabled');

  const value = node.props.value || '';

  return `${indentStr}<textarea ${classAttr}="${classes}" rows={${rows}} ${attrs.join(' ')}>\n${indentStr}  ${escapeJSX(value)}\n${indentStr}</textarea>`;
}

function renderSelect(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'select', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.required) attrs.push('required');
  if (node.props.disabled || hasState(node.props, 'disabled')) attrs.push('disabled');
  if (node.props.multiple) attrs.push('multiple');

  const optionsJSX = (node.options || []).map((opt: any) => {
    const selected = opt.selected ? ' defaultSelected' : '';
    return `    <option value="${escapeJSX(opt.value)}"${selected}>${escapeJSX(opt.label)}</option>`;
  }).join('\n');

  const placeholder = node.props.placeholder;
  const placeholderOption = placeholder
    ? `    <option value="" disabled defaultSelected>${escapeJSX(placeholder)}</option>\n`
    : '';

  return `${indentStr}<select ${classAttr}="${classes}" ${attrs.join(' ')}>
${placeholderOption}${optionsJSX}
${indentStr}</select>`;
}

function renderCheckbox(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'checkbox', node.props);
  const checked = node.checked;
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.value) attrs.push(`value="${escapeJSX(node.props.value)}"`);
  if (node.props.disabled || hasState(node.props, 'disabled')) attrs.push('disabled');

  const labelJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.label);

  return `${indentStr}<label ${classAttr}="${classes}">
${indentStr}  <input type="checkbox"${checked ? ' defaultChecked' : ''} ${attrs.join(' ')} />
${indentStr}  <span>${labelJSX}</span>
${indentStr}</label>`;
}

function renderRadio(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'radio', node.props);
  const checked = node.selected;
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.name) attrs.push(`name="${escapeJSX(node.props.name)}"`);
  if (node.props.value) attrs.push(`value="${escapeJSX(node.props.value)}"`);
  if (node.props.disabled || hasState(node.props, 'disabled')) attrs.push('disabled');

  return `${indentStr}<label ${classAttr}="${classes}">
${indentStr}  <input type="radio"${checked ? ' defaultChecked' : ''} ${attrs.join(' ')} />
${indentStr}  <span>${escapeJSX(node.label)}</span>
${indentStr}</label>`;
}

function renderRadioGroup(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const isInline = node.props?.inline;
  const classes = buildClasses(prefix, 'radio-group', node.props);
  const inlineClass = isInline ? ` ${prefix}radio-group-inline` : '';
  const classAttr = context.useClassName ? 'className' : 'class';

  const groupName = context.nextId('radio');

  const radios = (node.children || []).map((child: any) => {
    if (child.type === 'radio') {
      const modifiedChild = { ...child, props: { ...child.props, name: groupName } };
      return renderNode(modifiedChild, context, indent + 1);
    }
    return renderNode(child, context, indent + 1);
  }).join('\n');

  return `${indentStr}<div ${classAttr}="${classes}${inlineClass}">
${radios}
${indentStr}</div>`;
}

function renderIcon(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'icon', node.props);
  const iconName = node.props.name || 'default';
  const classAttr = context.useClassName ? 'className' : 'class';

  // Icon mapping
  const iconMap: Record<string, string> = {
    'home': '🏠', 'user': '👤', 'settings': '⚙️', 'search': '🔍',
    'star': '⭐', 'heart': '❤️', 'mail': '✉️', 'phone': '📞',
    'check': '✓', 'close': '✕', 'menu': '☰', 'more': '⋯',
    'default': '●'
  };

  const iconContent = iconMap[iconName] || iconMap['default'];

  return `${indentStr}<span ${classAttr}="${classes}" data-icon="${iconName}" aria-label="${iconName}">${iconContent}</span>`;
}

function renderContainer(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, `container-${node.containerType}`, node.props);
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}<div ${classAttr}="${classes}">
${childrenJSX}
${indentStr}</div>`;
}

function renderNav(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'nav', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 2)).join('\n');

  return `${indentStr}<nav ${classAttr}="${classes}">
${indentStr}  <div ${classAttr}="${prefix}nav-content">
${childrenJSX}
${indentStr}  </div>
${indentStr}</nav>`;
}

function renderNavItem(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'nav-item', node.props);
  const href = node.href || '#';
  const classAttr = context.useClassName ? 'className' : 'class';

  const contentJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content);

  return `${indentStr}<a href="${href}" ${classAttr}="${classes}">${contentJSX}</a>`;
}

function renderBrand(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'brand', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, 0)).join('');

  return `${indentStr}<div ${classAttr}="${classes}">${childrenJSX}</div>`;
}

function renderGrid(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'grid', node.props);
  const columns = node.columns || 3;
  const responsiveClass = buildResponsiveGridClasses(prefix, node.props?.responsive?.gridColumns);
  const gridClass = `${classes} ${prefix}grid-${columns}${responsiveClass ? ` ${responsiveClass}` : ''}`;
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}<div ${classAttr}="${gridClass}" style={{ '--grid-columns': ${columns} }${context.typescript ? ' as React.CSSProperties' : ''}}>
${childrenJSX}
${indentStr}</div>`;
}

function renderGridItem(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'grid-item', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}<div ${classAttr}="${classes}">
${childrenJSX}
${indentStr}</div>`;
}

function renderHeading(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const level = node.level || 1;
  const classes = buildClasses(prefix, `h${level}`, node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  const childrenJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content || '');

  const tag = `h${level}`;
  return `${indentStr}<${tag} ${classAttr}="${classes}">${childrenJSX}</${tag}>`;
}

function renderParagraph(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'paragraph', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  const childrenJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : (node.content ? escapeJSX(node.content) : '');

  return `${indentStr}<p ${classAttr}="${classes}">${childrenJSX}</p>`;
}

function renderText(node: any, _context: ReactRenderContext, _indent: number): string {
  return escapeJSX(node.content || '');
}

function renderImage(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'image', node.props);
  const src = node.src || '';
  const alt = node.alt || '';
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.props.width) attrs.push(`width="${node.props.width}"`);
  if (node.props.height) attrs.push(`height="${node.props.height}"`);

  return `${indentStr}<img src="${escapeJSX(src)}" alt="${escapeJSX(alt)}" ${classAttr}="${classes}" ${attrs.join(' ')} />`;
}

function renderLink(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'link', node.props);
  const href = node.href || '#';
  const classAttr = context.useClassName ? 'className' : 'class';

  const attrs: string[] = [];
  if (node.title) attrs.push(`title="${escapeJSX(node.title)}"`);

  const childrenJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content || '');

  return `${indentStr}<a href="${escapeJSX(href)}" ${classAttr}="${classes}" ${attrs.join(' ')}>${childrenJSX}</a>`;
}

function renderList(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'list', node.props);
  const tag = node.ordered ? 'ol' : 'ul';
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}<${tag} ${classAttr}="${classes}">
${childrenJSX}
${indentStr}</${tag}>`;
}

function renderListItem(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'list-item', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  const childrenJSX = node.children
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content || '');

  return `${indentStr}<li ${classAttr}="${classes}">${childrenJSX}</li>`;
}

function renderTable(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'table', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  const headerNode = node.children?.find((child: any) => child.type === 'table-header');
  const rowNodes = node.children?.filter((child: any) => child.type === 'table-row') || [];

  const headerJSX = headerNode ? renderNode(headerNode, context, indent + 1) : '';
  const rowsJSX = rowNodes.map((child: any) => renderNode(child, context, indent + 2)).join('\n');
  const bodyJSX = rowsJSX ? `\n${indentStr}  <tbody>\n${rowsJSX}\n${indentStr}  </tbody>` : '';

  return `${indentStr}<table ${classAttr}="${classes}">
${headerJSX}${bodyJSX}
${indentStr}</table>`;
}

function renderTableHeader(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const cellsJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 2)).join('\n');

  return `${indentStr}  <thead>
${indentStr}    <tr>
${cellsJSX}
${indentStr}    </tr>
${indentStr}  </thead>`;
}

function renderTableRow(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const cellsJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}    <tr>
${cellsJSX}
${indentStr}    </tr>`;
}

function renderTableCell(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const tag = node.header ? 'th' : 'td';
  const align = node.align || 'left';
  const classes = buildClasses(prefix, `table-cell ${prefix}align-${align}`, {});
  const classAttr = context.useClassName ? 'className' : 'class';

  const contentJSX = node.children && node.children.length > 0
    ? node.children.map((child: any) => renderNode(child, context, 0)).join('')
    : escapeJSX(node.content || '');

  return `${indentStr}      <${tag} ${classAttr}="${classes}">${contentJSX}</${tag}>`;
}

function renderBlockquote(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'blockquote', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';
  const childrenJSX = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).join('\n');

  return `${indentStr}<blockquote ${classAttr}="${classes}">
${childrenJSX}
${indentStr}</blockquote>`;
}

function renderCode(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const inline = node.inline !== false;
  const classAttr = context.useClassName ? 'className' : 'class';

  if (inline) {
    const classes = buildClasses(prefix, 'code-inline', {});
    return `${indentStr}<code ${classAttr}="${classes}">${escapeJSX(node.value)}</code>`;
  } else {
    const classes = buildClasses(prefix, 'code-block', {});
    const dataLang = node.lang ? ` data-lang="${escapeJSX(node.lang)}"` : '';
    return `${indentStr}<pre ${classAttr}="${classes}"><code${dataLang}>${escapeJSX(node.value)}</code></pre>`;
  }
}

function renderSeparator(node: any, context: ReactRenderContext, indent: number): string {
  const indentStr = repeatString('  ', indent);
  const { classPrefix: prefix } = context;
  const classes = buildClasses(prefix, 'separator', node.props);
  const classAttr = context.useClassName ? 'className' : 'class';

  return `${indentStr}<hr ${classAttr}="${classes}" />`;
}

function renderStateBlock(
  node: any,
  context: ReactRenderContext,
  indent: number,
  kind: 'loading-state' | 'empty-state' | 'error-state',
  title: string,
  iconName?: string,
): string {
  const indentStr = repeatString('  ', indent);
  const classAttr = context.useClassName ? 'className' : 'class';
  const classes = buildClasses(context.classPrefix, `container-${kind}`, node.props || {});
  const iconMarkup = iconName ? renderIcon({ props: { name: iconName } }, context, 0) : '';
  const children = (node.children || []).map((child: any) => renderNode(child, context, indent + 1)).filter(Boolean).join('\n');

  return `${indentStr}<div ${classAttr}="${classes}">
${indentStr}  <strong>${iconMarkup}${escapeJSX(title)}</strong>
${children ? `${children}\n` : ''}${indentStr}</div>`;
}

/**
 * Build CSS classes string from prefix, base class, and props
 */
function buildClasses(prefix: string, baseClass: string, props: any): string {
  const classes = new Set<string>([`${prefix}${baseClass}`]);

  if (props.variant) {
    classes.add(`${prefix}${baseClass}-${props.variant}`);
  }

  if (props.classes && Array.isArray(props.classes)) {
    props.classes.forEach((cls: string) => {
      if ((props.variant && cls === props.variant) || shouldSkipPrefixedClass(baseClass, cls)) {
        return;
      }
      classes.add(`${prefix}${cls}`);
    });
  }
  const states = getStates(props);
  states.forEach((state) => {
    classes.add(`${prefix}state-${state}`);
  });

  return Array.from(classes).join(' ');
}

function getStates(props: any): string[] {
  if (!props || typeof props !== 'object') {
    return [];
  }

  const states: string[] = [];

  if (typeof props.state === 'string' && props.state.trim()) {
    states.push(props.state.trim());
  }

  if (Array.isArray(props.states)) {
    props.states.forEach((state: unknown) => {
      if (typeof state === 'string' && state.trim() && !states.includes(state.trim())) {
        states.push(state.trim());
      }
    });
  }

  return states;
}

function hasState(props: any, state: string): boolean {
  return getStates(props).includes(state);
}

function buildResponsiveGridClasses(prefix: string, gridColumns?: Record<string, number>): string {
  if (!gridColumns || typeof gridColumns !== 'object') {
    return '';
  }

  const classes: string[] = [];
  Object.entries(gridColumns).forEach(([breakpoint, columns]) => {
    if (typeof columns === 'number' && columns > 0) {
      classes.push(`${prefix}grid-${breakpoint}-${columns}`);
    }
  });

  return classes.join(' ');
}

function shouldSkipPrefixedClass(baseClass: string, className: string): boolean {
  const normalizedClass = className.trim();

  if (baseClass !== 'grid') {
    return false;
  }

  return /^grid-\d+$/.test(normalizedClass) || /^(xs|sm|md|lg|xl|2xl):grid-\d+$/.test(normalizedClass);
}

function appendAnnotationJSX(
  rendered: string,
  node: WiremdNode,
  context: ReactRenderContext,
  indentStr: string
): string {
  if (!context.showAnnotations) {
    return rendered;
  }

  const annotationText = buildAnnotationText((node as any).props);
  if (!annotationText) {
    return rendered;
  }

  const classAttr = context.useClassName ? 'className' : 'class';
  const annotation = `${indentStr}<aside ${classAttr}="${context.classPrefix}annotation-callout">${escapeJSX(annotationText)}</aside>`;
  return `${rendered}\n${annotation}`;
}

function isAnnotationOnlyNode(node: WiremdNode): boolean {
  if (node.type !== 'container') {
    return false;
  }

  const props: any = (node as any).props;
  if (!props || typeof props !== 'object') {
    return false;
  }

  if (props.annotationRole === 'note') {
    return true;
  }

  return Array.isArray(props.classes) && props.classes.includes('annotation-note');
}

function buildAnnotationText(props: any): string {
  if (!props || typeof props !== 'object') {
    return '';
  }

  const entries: string[] = [];
  const seen = new Set<string>();

  const push = (prefix: string, value: unknown): void => {
    if (typeof value !== 'string' || !value.trim()) {
      return;
    }
    const text = prefix ? `${prefix}: ${value.trim()}` : value.trim();
    if (!seen.has(text)) {
      seen.add(text);
      entries.push(text);
    }
  };

  push('Annotation', props.annotation);
  push('TODO', props.todo);
  push('Version', props.versionNote);

  if (Array.isArray(props.annotations)) {
    props.annotations.forEach((annotation: any) => {
      if (!annotation || typeof annotation !== 'object') {
        return;
      }

      if (typeof annotation.todo === 'string' && annotation.todo.trim()) {
        push('TODO', annotation.todo);
      } else if (typeof annotation.version === 'string' && annotation.version.trim()) {
        push('Version', annotation.version);
      } else if (typeof annotation.note === 'string' && annotation.note.trim()) {
        push('Note', annotation.note);
      } else if (typeof annotation.text === 'string' && annotation.text.trim()) {
        push('Annotation', annotation.text);
      }
    });
  }

  return entries.join(' | ');
}

/**
 * Escape JSX special characters
 */
function escapeJSX(text: string): string {
  if (!text) return '';

  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/{/g, '&#123;')
    .replace(/}/g, '&#125;');
}
